-- AlterTable
ALTER TABLE "Recipe" ALTER COLUMN "preNotes" SET NOT NULL,
ALTER COLUMN "preNotes" SET DATA TYPE TEXT,
ALTER COLUMN "postNotes" SET NOT NULL,
ALTER COLUMN "postNotes" SET DATA TYPE TEXT;
